// Copies Ask DeepGrid from the DG32 site (github.com/shekerkamma/deepgrid-dr-silicon) into this showcase's
// Ask DeepGrid view (#briefing). The DG32 repo is the source of truth for the whole pipeline: graphify
// builds graphify-out/, scripts/build-unified-graphrag.py turns it into app/data/graphrag-unified-index.json,
// and `npm run build:semantic` embeds it into public/graphrag/. This script copies the results so both sites
// answer from the same content, index, curated themes and routing thresholds.
//
//   DR_SITE=/path/to/deepgrid-dr-site npm run sync:ask      (default: ../../../deepgrid-dr-site)
//   npm run sync:ask -- --check                             (exit 1 if anything differs; copies nothing)
//
// Code, data, eval and scripts are copied byte-for-byte, so `--check` is a plain comparison. The one
// generated file is app/ask.css: the DG32 stylesheets (globals, ux, dr) nested under `.dg-ask`, so they style the Ask view
// and cannot restyle the rest of the showcase. Only :root tokens (renamed `&`) and @keyframes stay global.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DR = path.resolve(process.env.DR_SITE || path.join(ROOT, '../../../deepgrid-dr-site'));
const CHECK = process.argv.includes('--check');
if (!fs.existsSync(path.join(DR, 'app/ask.tsx'))) throw new Error(`no DG32 site checkout at ${DR} (set DR_SITE)`);

const FILES = [
  'app/ask.tsx', 'app/council-view.tsx', 'app/documents-data.ts',
  'app/data/deepgrid-knowledge.ts', 'app/data/graphrag-engine.ts', 'app/data/graphrag-unified-index.json',
  'app/data/multi-agent-engine.ts', 'app/data/semantic.ts', 'app/data/theme-examples.ts',
  'scripts/ask-routing-eval.json', 'scripts/build-semantic-index.mjs', 'scripts/check-semantic.mjs', 'scripts/copy-runtime.mjs',
  'public/graphrag/semantic.json', 'public/graphrag/semantic.bin',
  'public/downloads/graph.html', 'public/downloads/graph.json', 'public/downloads/GRAPH_REPORT.md',
];
const TREES = ['public/models', 'public/downloads/docs'];

const walk = dir => fs.readdirSync(path.join(DR, dir), {withFileTypes: true})
  .flatMap(e => e.isDirectory() ? walk(path.join(dir, e.name)) : [path.join(dir, e.name)]);
const all = [...FILES, ...TREES.flatMap(walk)];

// Split a stylesheet into top-level statements, respecting braces, strings and comments.
function statements(css) {
  const out = []; let depth = 0, start = 0, quote = null;
  for (let i = 0; i < css.length; i++) {
    const c = css[i];
    if (quote) { if (c === '\\') i++; else if (c === quote) quote = null; continue; }
    if (c === '"' || c === "'") { quote = c; continue; }
    if (c === '/' && css[i + 1] === '*') { const end = css.indexOf('*/', i + 2); i = end < 0 ? css.length : end + 1; continue; }
    if (c === '{') depth++;
    else if (c === '}' && --depth === 0) { out.push(css.slice(start, i + 1).trim()); start = i + 1; }
    else if (c === ';' && depth === 0) { out.push(css.slice(start, i + 1).trim()); start = i + 1; }
  }
  return out.filter(Boolean);
}
function scopedCss() {
  const global = [], nested = [];
  for (const file of ['app/globals.css', 'app/ux.css', 'app/dr.css']) {
    for (const s of statements(fs.readFileSync(path.join(DR, file), 'utf8'))) {
      const body = s.replace(/^\/\*[\s\S]*?\*\/\s*/g, '');
      // Tailwind directives and base keyframes already come from the showcase's own globals.css
      if (/^@(import|custom-variant|theme|layer|plugin|source|utility|variant|config)\b/.test(body)) continue;
      if (/^@(-webkit-)?keyframes\b/.test(body)) { if (file === 'app/dr.css') global.push(body); continue; }
      // design tokens become custom properties on the scope element, so descendants inherit them
      else nested.push(body.replace(/(^|[{};,\s]):root(\s*,\s*\.dark)?(?=\s*[{,])/g, '$1&'));
    }
  }
  return `/* GENERATED by scripts/sync-ask.mjs from deepgrid-dr-site app/globals.css + ux.css + dr.css. Do not edit. */\n` +
    global.join('\n') + `\n.dg-ask{\n${nested.join('\n')}\n}\n`;
}

let differ = 0;
const put = (rel, data) => {
  const to = path.join(ROOT, rel);
  if (fs.existsSync(to) && Buffer.compare(fs.readFileSync(to), Buffer.from(data)) === 0) return;
  differ++;
  if (CHECK) { console.error(`differs: ${rel}`); return; }
  fs.mkdirSync(path.dirname(to), {recursive: true});
  fs.writeFileSync(to, data);
};
for (const rel of all) put(rel, fs.readFileSync(path.join(DR, rel)));
put('app/ask.css', scopedCss());

if (CHECK && differ) { console.error(`\n${differ} Ask DeepGrid file(s) differ from ${DR}. Run: npm run sync:ask`); process.exit(1); }
console.log(`${CHECK ? 'in sync' : `synced ${differ} changed file(s)`}: ${all.length + 1} Ask DeepGrid files from ${DR}`);
