// DeepGrid Grounded Architecture Documents & Specifications Data Registry
// All 6 Core Authoritative Design Documents (Docs #1..#6) + 3 Platform Deliverables

export interface GroundedDoc {
  id: string;
  badge: string;
  docNum: string;
  title: string;
  subtitle: string;
  group: 'core' | 'platform';
  subsystem: string;
  specFile: string;
  specFileName: string;
  pdfFile: string;
  pdfFileName: string;
  fileSizeMd: string;
  fileSizePdf: string;
  pdfPageCount: string;
  stats: { label: string; value: string }[];
  summary: string;
  highlights: string[];
  defaultQuery: string;
  queryDocId: 'doc1' | 'doc2' | 'doc3' | 'doc4' | 'doc5' | 'doc6' | 'doc7' | 'doc8' | 'doc9';
}

export const groundedDocuments: GroundedDoc[] = [
  {
    id: 'doc1',
    badge: 'DOC #1 · EDGE AI COMPUTATION',
    docNum: '01',
    title: 'Thirty Use Cases, No Accelerator',
    subtitle: '50 MHz RV32IM edge AI compute envelope, 19 lightweight models, fixed-point DSP pipeline & CWRU audit',
    group: 'core',
    subsystem: 'Edge AI & Diagnostics',
    specFile: './downloads/docs/deepgrid-dg32-ai-architecture.md',
    specFileName: 'deepgrid-dg32-ai-architecture.md',
    pdfFile: './downloads/docs/deepgrid-dg32-ai-30-use-cases.pdf',
    pdfFileName: 'deepgrid-dg32-ai-30-use-cases.pdf',
    fileSizeMd: '7.3 KB',
    fileSizePdf: '414 KB',
    pdfPageCount: '12 pages',
    stats: [
      { label: 'Compute Engine', value: '50 MHz RV32IM (Zero NPU)' },
      { label: 'Scalar Ceiling', value: '12.5 MMAC/s (int8)' },
      { label: 'RAM Ceiling', value: '16.5 KB SRAM budget' },
      { label: 'Standard Compliance', value: 'ISO 13373 / 20816 / 20958' },
    ],
    summary: 'Formal proof that high-accuracy industrial condition monitoring and predictive diagnostics do not require heavy transformer acceleration or multi-watt NPU arrays. By exploiting the architectural inversion that comparisons and table lookups cost almost nothing on an integer CPU, tree ensembles achieve parity with deep learning (95.6% vs 97–100% on CWRU bearing benchmarks) while requiring zero multiplications and running 50–500× faster.',
    highlights: [
      '12.5 MMAC/s integer budget leaves 82% CPU headroom at 10 kHz FOC current loop rate',
      'Single-bin Goertzel DFT replaces multi-megabyte FFT buffers for broken rotor bar detection',
      'Documents non-monotonic Kurtosis trap: kurtosis drops as spall rounds over, requiring RMS cross-checking',
      'Uncovers critical 100% synthetic accuracy leakage in academic CWRU bearing benchmark datasets',
    ],
    defaultQuery: 'How does DG32-LITE run AI without a hardware accelerator?',
    queryDocId: 'doc1',
  },
  {
    id: 'doc2',
    badge: 'DOC #2 · 10-SKU COMPENDIUM',
    docNum: '02',
    title: 'Technical Annex v3 (10 SKUs, D100 & SDV)',
    subtitle: '10-chip silicon compendium, D100 tactical drone SoC, DG SDV zonal E/E platform & 3-phase roadmap',
    group: 'core',
    subsystem: 'Portfolio & System Platforms',
    specFile: './downloads/docs/deepgrid-sku-compendium-architecture.md',
    specFileName: 'deepgrid-sku-compendium-architecture.md',
    pdfFile: './downloads/docs/deepgrid-sku-compendium-technical-annex-v3.pdf',
    pdfFileName: 'deepgrid-sku-compendium-technical-annex-v3.pdf',
    fileSizeMd: '7.5 KB',
    fileSizePdf: '4.95 MB',
    pdfPageCount: '14 pages',
    stats: [
      { label: 'Silicon Portfolio', value: '10 SKUs (180nm BCD to 130nm SiGe)' },
      { label: 'Tactical Drone', value: 'D100 Drone SoC with failsafe island' },
      { label: 'Vehicle Architecture', value: 'DG SDV Zonal E/E Reference' },
      { label: 'Fab Execution', value: 'SkyWater → SCL Mohali → Dholera 28nm' },
    ],
    summary: 'The comprehensive 10-SKU silicon catalog systematically targeting $9B of foreign merchant silicon. Covers mature-node fabrication across 180nm BCD, 130nm CMOS, and IHP 130nm SiGe (350 GHz fT). Details the D100 dual-quad tactical drone SoC with hardware failsafe island, the DG SDV zonal software-defined vehicle platform, and multi-die organic substrate SiP packaging.',
    highlights: [
      '10 SKUs replacing TI, ST, and ADI chips across Indian defence and industrial sectors',
      'D100 drone platform combines quad RV64 application cores with isolated RV32 real-time failsafe core',
      'DG SDV zonal architecture eliminates 38 kg of wire harness through 4 zonal controllers',
      'Organic substrate multi-die packaging achieves 25 µm line/space without silicon interposer costs',
    ],
    defaultQuery: 'Compare DG32 with STM32G0 in pinout, cost, and latency',
    queryDocId: 'doc2',
  },
  {
    id: 'doc3',
    badge: 'DOC #3 · HARDWARE DSHOT RX RTL',
    docNum: '03',
    title: 'dgrid_dshot_rx RTL Specification',
    subtitle: 'Hardware DShot receive engine, bidirectional GCR 4b→5b eRPM telemetry reply & pad-ring reuse',
    group: 'core',
    subsystem: 'High-Speed Motor Telemetry',
    specFile: './downloads/docs/deepgrid-dshot-rx-architecture.md',
    specFileName: 'deepgrid-dshot-rx-architecture.md',
    pdfFile: './downloads/docs/deepgrid-dshot-rx-block-spec.pdf',
    pdfFileName: 'deepgrid-dshot-rx-block-spec.pdf',
    fileSizeMd: '11.3 KB',
    fileSizePdf: '353 KB',
    pdfPageCount: '8 pages',
    stats: [
      { label: 'Data Rates', value: 'DShot150 / 300 / 600 / 1200' },
      { label: 'Telemetry Engine', value: 'Hardware GCR 4b→5b eRPM reply' },
      { label: 'Memory Bus', value: 'Slot 0xC APB memory-mapped' },
      { label: 'Floorplan Area', value: '28 KB vs 32 KB SRAM layout lever' },
    ],
    summary: 'Complete RTL engineering specification for dgrid_dshot_rx: offloads ESC motor signal decoding and bidirectional eRPM telemetry reply entirely into deterministic hardware logic. Features glitch-free pad-ring direction reuse without external analog multiplexers, early-abort frame suppression, and floorplan trade-off recovering 4,800 µm² die area.',
    highlights: [
      'Zero-CPU overhead motor command capture and validation up to DShot1200 rates',
      'Autonomous GCR 4b→5b eRPM packet assembly and transmission without software intervention',
      'Bidirectional GPIO pad-ring reuse with deterministic turnaround timing',
      '28 KB vs 32 KB SRAM floorplan trade-off analysis for sky130 multi-project shuttle packaging',
    ],
    defaultQuery: 'Why is DShot receive and bidirectional telemetry implemented in hardware rather than firmware?',
    queryDocId: 'doc3',
  },
  {
    id: 'doc4',
    badge: 'DOC #4 · DUAL-DOMAIN SOC & ATTENTION',
    docNum: '04',
    title: 'DG32-2DOM Architecture & Block Definition',
    subtitle: 'Dual 50/114 MHz clocks, 4-phase CDC bridges, INT8 attention engine & AVIP diagnostics',
    group: 'core',
    subsystem: 'Condition Monitoring & Attention',
    specFile: './downloads/docs/deepgrid-2dom-architecture.md',
    specFileName: 'deepgrid-2dom-architecture.md',
    pdfFile: './downloads/docs/deepgrid-dg32-2dom-system-architecture.pdf',
    pdfFileName: 'deepgrid-dg32-2dom-system-architecture.pdf',
    fileSizeMd: '9.3 KB',
    fileSizePdf: '79 KB',
    pdfPageCount: '24 pages',
    stats: [
      { label: 'Clock Partition', value: '50 MHz Control · 114 MHz Attention' },
      { label: 'CDC Mechanism', value: '4-Phase Asynchronous Handshake' },
      { label: 'Attention Core', value: 'INT8 Multi-Head (40-bit Accumulator)' },
      { label: 'Sensorless MCSA', value: 'AVIP Stator Current Bearing Analysis' },
    ],
    summary: 'Authoritative system architecture of DG32-2DOM: adds an INT8 multi-head self-attention engine on an independent 114 MHz clock domain alongside the frozen 50 MHz lockstep control core. Robust 4-phase CDC bridges isolate domains so condition monitoring cannot stall the motor control loop. Utilizes AVIP stator current signature analysis to detect bearing faults with zero additional sensor BOM.',
    highlights: [
      'Rigorous dual-clock domain isolation: control loop worst-case execution time guaranteed untouched',
      '40-bit accumulator headroom prevents INT8 softmax overflow and numerical saturation',
      'AVIP stator current diagnostics isolate inner/outer race bearing faults without accelerometers',
      '18 on-die SRAM macros occupying 86% of sky130 active die area with positive timing slack',
    ],
    defaultQuery: 'How do the 50 MHz core and 114 MHz attention clock domains communicate via CDC bridges?',
    queryDocId: 'doc4',
  },
  {
    id: 'doc5',
    badge: 'DOC #5 · DEFENCE & ECONOMIC STRATEGY',
    docNum: '05',
    title: "Mature-Node Silicon for India's Defence (Whitepaper v3)",
    subtitle: '$9B mature-node import funnel, 198-day loop, 10x NRE dismantling & DAP-2020 Make-II statutory moats',
    group: 'core',
    subsystem: 'Geopolitics & Strategic Moats',
    specFile: './downloads/docs/deepgrid-mature-silicon-architecture.md',
    specFileName: 'deepgrid-mature-silicon-architecture.md',
    pdfFile: './downloads/docs/deepgrid-mature-node-silicon-master-whitepaper-v3.pdf',
    pdfFileName: 'deepgrid-mature-node-silicon-master-whitepaper-v3.pdf',
    fileSizeMd: '10.7 KB',
    fileSizePdf: '5.62 MB',
    pdfPageCount: '71 pages',
    stats: [
      { label: 'Import Funnel', value: '$9B Mature-Node Defence Market' },
      { label: 'Tapeout Cadence', value: '198-Day Shuttle Loop' },
      { label: 'NRE Economics', value: '₹0.6–1.2 Cr (10x NRE reduction)' },
      { label: 'Legal Framework', value: 'DAP-2020 Make-II · PIL-1..5 · SRIJAN' },
    ],
    summary: "The foundational 71-page master whitepaper establishing India's mature-node semiconductor doctrine. Proves that 84% of defence and industrial silicon needs are mature nodes (≥65nm). Demonstrates how open-source EDA and shared MPW shuttles dismantle tapeout NRE from ₹12 Cr to ₹0.8 Cr, creates statutory moats through 'Boxes, Not Chips' integration under DAP-2020, and models Chinese supply disruption resilience.",
    highlights: [
      '$9B mature-node import funnel prioritized across 10 critical defence semiconductor SKUs',
      '198-day tapeout loop from RTL freeze to packaged silicon delivery using OpenLane EDA',
      'Statutory moats under DAP-2020 Make-II and Ministry of Defence positive indigenisation lists',
      'Rigorous Charlie Munger inversion audits and strict stop-rules S1–S4',
    ],
    defaultQuery: 'How does the 198-day tapeout loop achieve 10x NRE reduction?',
    queryDocId: 'doc5',
  },
  {
    id: 'doc6',
    badge: 'DOC #6 · DATASHEETS & PINOUT',
    docNum: '06',
    title: 'Preliminary Engineering Datasheets & Package Pinout',
    subtitle: '64-pin QFN 9×9mm pin mapping, 100% LITE/2DOM compatibility, supply sequencing & ROM boot',
    group: 'core',
    subsystem: 'Packaging, Clocks & Electrical Rules',
    specFile: './downloads/docs/deepgrid-datasheets-engineering-spec.md',
    specFileName: 'deepgrid-datasheets-engineering-spec.md',
    pdfFile: './downloads/docs/deepgrid-datasheets-qfn64.pdf',
    pdfFileName: 'deepgrid-datasheets-qfn64.pdf',
    fileSizeMd: '13.6 KB',
    fileSizePdf: '78 KB',
    pdfPageCount: '24 pages',
    stats: [
      { label: 'Package Spec', value: 'QFN-64 (9×9 mm, 0.5 mm pitch)' },
      { label: 'Signal Pins', value: '44 Signal Pins across 11 groups' },
      { label: 'Supply Rails', value: '1.8V Core · 3.3V I/O (Sequenced)' },
      { label: 'Compatibility', value: '100% Socket Match (LITE & 2DOM)' },
    ],
    summary: 'Authoritative preliminary engineering datasheet for DG32-LITE and DG32-2DOM in QFN-64. Guarantees 100% drop-in mechanical and electrical pin compatibility across both chips. Mandates strict power supply sequencing (3.3V I/O must lead 1.8V core by ≥1 ms to protect ESD rail diodes), defines 64 KB mask boot ROM operations, and maps all 44 signal pins.',
    highlights: [
      'Identical 64-pin footprint allows one PCB layout to take either DG32-LITE or DG32-2DOM',
      'Strict power supply sequencing protects internal ESD rail clamps from latch-up breakdown',
      '44 functional signal pins organized into 11 functional clusters with dedicated return paths',
      '64 KB autonomous boot ROM with flash header validation and fallback UART monitor',
    ],
    defaultQuery: 'What are the power supply sequencing rules between 1.8V and 3.3V?',
    queryDocId: 'doc6',
  },
  {
    id: 'doc-d100',
    badge: 'PLATFORM · D100 DRONE SOC',
    docNum: 'S1',
    title: 'D100 Tactical Drone Platform Architecture',
    subtitle: 'Dual-quad heterogeneous compute with isolated hardware flight failsafe island',
    group: 'platform',
    subsystem: 'Tactical Drone Flight Systems',
    specFile: './downloads/docs/deepgrid-d100-architecture.md',
    specFileName: 'deepgrid-d100-architecture.md',
    pdfFile: './downloads/docs/deepgrid-sku-compendium-technical-annex-v3.pdf',
    pdfFileName: 'deepgrid-sku-compendium-technical-annex-v3.pdf',
    fileSizeMd: '12.1 KB',
    fileSizePdf: '4.95 MB',
    pdfPageCount: 'Sheet 09',
    stats: [
      { label: 'Core Topology', value: 'Quad RV64 (App) + Quad RV32 (Real-Time)' },
      { label: 'Failsafe Domain', value: 'Isolated Hardware Failsafe Island' },
      { label: 'Motor Channels', value: '8 × Dedicated DShot Outputs' },
      { label: 'Avionics Bus', value: 'Dual CAN-FD & High-Speed SPI' },
    ],
    summary: 'Heterogeneous multi-core SoC for tactical unmanned aerial systems. Partitions flight compute into high-performance vision/navigation (Quad RV64) and hard real-time flight control (Quad RV32), backed by a physically isolated hardware failsafe island that takes over motor control upon main OS hang or communication loss.',
    highlights: [
      'Hardware failsafe island executes emergency return-to-launch (RTL) independent of Linux host',
      '8 hardware-timed DShot motor channels with microsecond-level synchronization',
      'Direct hardware cryptographic authentication for secure datalinks',
      'Sub-watt low-power standby modes for extended loiter missions',
    ],
    defaultQuery: 'How does the D100 drone hardware failsafe island work?',
    queryDocId: 'doc2',
  },
  {
    id: 'doc-sdv',
    badge: 'PLATFORM · SDV ZONAL E/E',
    docNum: 'S2',
    title: 'DG SDV Software-Defined Vehicle Zonal Architecture',
    subtitle: 'Distributed zonal controllers eliminating vehicle wire harness mass and latency',
    group: 'platform',
    subsystem: 'Automotive Zonal Controllers',
    specFile: './downloads/docs/deepgrid-sdv-architecture.md',
    specFileName: 'deepgrid-sdv-architecture.md',
    pdfFile: './downloads/docs/deepgrid-sku-compendium-technical-annex-v3.pdf',
    pdfFileName: 'deepgrid-sku-compendium-technical-annex-v3.pdf',
    fileSizeMd: '8.0 KB',
    fileSizePdf: '4.95 MB',
    pdfPageCount: 'Sheet 10',
    stats: [
      { label: 'Weight Saved', value: '38 kg wiring harness reduction' },
      { label: 'Network Latency', value: '<50 µs deterministic CAN-XL' },
      { label: 'Zone Clusters', value: '4 × Zonal Controllers' },
      { label: 'Safety ASIL', value: 'ASIL-D Decomposition' },
    ],
    summary: 'Automotive zonal E/E reference architecture replacing complex point-to-point body harnesses with 4 distributed zonal gateways. Uses DG32 silicon to aggregate sensors, motor actuators, and lighting at each quadrant, slashing wiring harness mass by 38 kg and enabling centralized software-defined updates.',
    highlights: [
      '38 kg harness weight elimination directly improving electric vehicle range',
      'Deterministic CAN-XL and 10BASE-T1S automotive Ethernet backbones',
      'Local hardware motor control and current sensing for high-reliability body actuators',
      'Full hardware safety fault confinement adhering to ISO 26262 ASIL-D',
    ],
    defaultQuery: 'How does the DG SDV architecture eliminate wire harnesses via zonal controllers?',
    queryDocId: 'doc2',
  },
  {
    id: 'doc-three-factory',
    badge: 'STRATEGY · SOVEREIGN SILICON',
    docNum: 'S3',
    title: 'Three-Factory Sovereign Silicon Architecture',
    subtitle: 'Strategic manufacturing arbitrage across SkyWater, SCL Mohali, and Dholera 28nm fabs',
    group: 'platform',
    subsystem: 'Manufacturing & Fab Strategy',
    specFile: './downloads/docs/deepgrid-three-factory-architecture.md',
    specFileName: 'deepgrid-three-factory-architecture.md',
    pdfFile: './downloads/docs/deepgrid-mature-node-silicon-master-whitepaper-v3.pdf',
    pdfFileName: 'deepgrid-mature-node-silicon-master-whitepaper-v3.pdf',
    fileSizeMd: '9.6 KB',
    fileSizePdf: '5.62 MB',
    pdfPageCount: 'Section 4',
    stats: [
      { label: 'Foundry Network', value: 'SkyWater · SCL Mohali · Dholera 28nm' },
      { label: 'Node Distribution', value: '180nm BCD · 130nm CMOS · 28nm Planar' },
      { label: 'Supply Resilience', value: 'Sanction-proof multi-foundry PDKs' },
      { label: 'Economic Model', value: '₹10 Cr Capital Efficiency' },
    ],
    summary: "Geopolitical and fab-arbitrage blueprint for Indian semiconductor sovereignty. Aligns design tooling so RTL can port seamlessly between US open-access fabs (SkyWater), Indian strategic fabs (SCL Mohali 180nm), and emerging commercial mega-fabs (Tata Dholera 28nm), guaranteeing supply continuity across international supply crunches.",
    highlights: [
      'Multi-foundry PDK portability preventing vendor lock-in to single fabs',
      'Zero-NRE open-source toolchain (OpenLane/Magic/KLayout) validated on test silicon',
      'Strategic arbitrage between high-voltage BCD (actuators) and dense CMOS (controllers)',
      "Proof of concept for India's ₹10 Cr sovereign chip initiative",
    ],
    defaultQuery: 'What is the three-factory fab arbitrage model?',
    queryDocId: 'doc5',
  },
];

// --- Showcase content (this site): Doc #7-#9. Their source files are not published, so they carry no PDF;
// answers link to the place on this page that shows each passage instead.
const showcaseDoc = (id: 'doc7' | 'doc8' | 'doc9', docNum: string, title: string, subtitle: string, subsystem: string, summary: string,
  highlights: string[], defaultQuery: string): GroundedDoc => ({id, badge: `DOC #${Number(docNum)} · ${subsystem.toUpperCase()}`, docNum, title, subtitle,
  group: 'core', subsystem, specFile: '', specFileName: '', pdfFile: '', pdfFileName: '', fileSizeMd: '', fileSizePdf: '', pdfPageCount: '',
  stats: [], summary, highlights, defaultQuery, queryDocId: id});
groundedDocuments.push(
  showcaseDoc('doc7', '07', 'Product Portfolio (15 Products, 104-Slide Deck)', 'Fifteen products on one 28 nm SoC2 die', 'Product Portfolio',
    'The fifteen DeepGrid products, from the ₹50,000 smart mirror to the ₹4 lakh truck kit, built on one shared 57 mm² SoC2 die.',
    ['Dossiers for all fifteen products: price, FY2032 revenue plan, margin, signal chain, key dependency', 'The 104-slide portfolio deck with speaker notes'],
    'How do the fifteen products fit together?'),
  showcaseDoc('doc8', '08', 'Investment & Information Memoranda', 'Thesis, demand, strategy, the round and the risks', 'Investment Case',
    'The investment memorandum, the Information Memoranda (June and v2), the BP1A India and BP1B USA plans, and the research and audits behind them.',
    ['Legislated ADAS demand for Indian commercial vehicles', 'The strategic choice and where the documents disagree'], 'Why invest in DeepGrid?'),
  showcaseDoc('doc9', '09', 'Financial Model & Business Plan', 'Revenue, margins, use of funds and runway', 'Financials',
    'Financial Model v3 (Sept 2026) and Business Plan v2: revenue build, P&L, use of funds, tapeout unit economics and cash runway. Management projections.',
    ['₹45 Cr equity plus ₹10 Cr CGTMSE debt', 'The two workbooks disagree on FY2032 revenue'], 'How does revenue grow to FY2032?'));
