'use client';
import {ArrowLeft,ArrowRight,CheckCircle2,Users,Package,ShieldAlert} from 'lucide-react';
import data from './use-cases.json';
const summaries=[
 {title:'Forward-path perception',buyer:'Braking Tier-1s & commercial-vehicle OEMs',supply:'A tracked object list with confidence, range and time-to-collision.',group:'Road Autonomy'},
 {title:'Fewer nuisance alerts',buyer:'Validation teams & pilot fleets',supply:'An equal-scope benchmark of false alerts and detection performance.',group:'Road Autonomy'},
 {title:'Blind spots & moving off',buyer:'Cab engineers, bus builders & fleet operators',supply:'Side and front near-field perception from a shared processing core.',group:'Road Autonomy'},
 {title:'Driver drowsiness',buyer:'Fleet safety & OEM homologation teams',supply:'An in-cab monitoring pipeline and the supporting participant study.',group:'Sensors & Robotics'},
 {title:'Lane departure warning',buyer:'ADAS integrators & highway fleets',supply:'A drivable-corridor estimate, departure alerts and an unavailable state.',group:'Road Autonomy'},
 {title:'Government & PSU fleets',buyer:'State transport, PSU & municipal procurement',supply:'An FPGA perception kit packaged for local-content procurement.',group:'Silicon & Compute'}
];
export default function UseCases({selected,onSelect,onProducts}:{selected:string;onSelect:(id:string)=>void;onProducts:(category:string)=>void}){
 const i=data.cases.findIndex(c=>c.id===selected),item=data.cases[i],summary=summaries[i];
 return <section className="usecase-explorer" aria-label="Business use cases">
 {!item?<><header className="usecase-intro"><div><h2>Six customer applications</h2><p>Choose an application to see the buyer, deliverable and evidence required to move forward.</p></div><span>6 use cases</span></header>
 <div className="usecase-grid">{data.cases.map((c,n)=><article className="usecase-card" key={c.id}><span className="usecase-code">{c.id}</span><h3>{summaries[n].title}</h3><dl><div><dt>Buyer</dt><dd>{summaries[n].buyer}</dd></div><div><dt>DeepGrid delivers</dt><dd>{summaries[n].supply}</dd></div></dl><button onClick={()=>onSelect(c.id)}>Explore use case <ArrowRight size={17}/></button></article>)}</div>
 <aside className="usecase-boundary"><ShieldAlert size={22}/><div><h3>Where DeepGrid’s responsibility ends</h3><p>DeepGrid supplies perception. The integrator retains responsibility for brake actuation, calibration, homologation and warranty.</p></div></aside>
 <section className="usecase-plan"><h2>The 90-day execution plan</h2><div>{data.sequence.map((s,n)=><article key={s.period}><span>0{n+1}</span><h3>{s.period}</h3><ul>{s.action.split(' · ').map(a=><li key={a}>{a}</li>)}</ul><p><strong>Owner</strong> {s.owner}</p></article>)}</div></section>
 <details className="usecase-source"><summary>Source timetable and capital boundaries</summary><p>The following dates and requirements are reproduced from the management dossier.</p><div className="usecase-table"><table><caption>Timetable stated in the source materials</caption><thead><tr>{['Function','Jan 2027','Oct 2027','Jan 2028','H1 2028'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.timetable.map(row=><tr key={row.label}><th>{row.label}</th>{row.milestones.map((v,n)=><td key={n}>{v}</td>)}</tr>)}</tbody></table></div><h3>Capital exclusions in the source plan</h3><p>{data.capital}</p></details></>:
 <><nav className="usecase-back" aria-label="Use-case navigation"><button onClick={()=>onSelect('')}><ArrowLeft size={17}/>All six use cases</button><span>{i+1} of 6</span></nav>
 <header className="usecase-detail-heading"><span className="usecase-code">{item.id}</span><h2>{summary.title}</h2><p>{summary.supply}</p><button className="text-link" onClick={()=>onProducts(summary.group)}>Browse {summary.group.toLowerCase()} products <ArrowRight size={16}/></button></header>
 <div className="usecase-facts"><article><Users size={21}/><h3>Who buys it</h3><p>{summary.buyer}</p></article><article><Package size={21}/><h3>What DeepGrid supplies</h3><p>{item.supply}</p></article><article><CheckCircle2 size={21}/><h3>Acceptance gate</h3><p>{item.gate}</p></article><article><ShieldAlert size={21}/><h3>Main dependency or risk</h3><p>{item.risk}</p></article></div>
 <section className="usecase-workflow"><h3>How it works</h3><ol>{item.steps.map((step,n)=><li key={step}><span>{n+1}</span><p>{step}</p></li>)}</ol></section>
 <details className="usecase-source"><summary>Technical context & source evidence</summary><h3>Challenge</h3><p>{item.challenge}</p><dl><div><dt>Standard or procurement framework</dt><dd>{item.standard}</dd></div><div><dt>Timing stated in the source</dt><dd>{item.dates}</dd></div><div><dt>Stakeholders</dt><dd>{item.buyer}</dd></div><div><dt>Organisations</dt><dd>{item.organisations}</dd></div></dl><div className="usecase-source-metrics">{item.stats.map(stat=><div key={stat.label}><strong>{stat.value}</strong><span>{stat.label}</span><p>{stat.note}</p></div>)}</div><p className="usecase-source-note">Source: DeepGrid investment memorandum, Part III. Dates, requirements and performance claims retain their original management-source context.</p></details>
 <nav className="usecase-pagination" aria-label="Adjacent use cases">{i>0?<button onClick={()=>onSelect(data.cases[i-1].id)}><ArrowLeft size={16}/>{summaries[i-1].title}</button>:<button onClick={()=>onSelect('')}><ArrowLeft size={16}/>All use cases</button>}{i<5&&<button onClick={()=>onSelect(data.cases[i+1].id)}>{summaries[i+1].title}<ArrowRight size={16}/></button>}</nav></>}
 </section>
}
